<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org"> 
    <info organisation="org.apache.easyant" module="myapp-parent" revision="0.2" status="integration" >
        <ea:property name="test.property" value="myvalue"/>
        <ea:plugin organisation="mycompany" module="modulewithtarget" revision="0.1" inherit-scope="child" />
        <ea:plugin organisation="mycompany" module="simplepluginwithproperties" revision="0.1" inheritable="false" my.property="myvalue"/>
        <ea:bindtarget target="modulewithtarget:mytarget" extensionOf="package" inherit-scope="child"/>
    </info>
    <configurations>
        <conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf"/>
        <conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
    </configurations>
</ivy-module>
