<!--
	Copyright 2009 the EasyAnt project

	See the NOTICE file distributed with this work for additional information
	regarding copyright ownership.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org">
	<info module="runsTest" status="integration" >
        <extends organisation="org.apache.easyant" module="test-junit-jar-testJar" revision="latest.integration" location="../module.ivy"/>
		<description>Runs a test jar defined in another module.</description>
		<ea:build mrid="org.apache.easyant.buildtypes#build-std-java;0.2">
            <ea:property name="test.scan.path" value="true"/>
        </ea:build>
	</info>
	<dependencies>
        <dependency org="org.apache.easyant" name="definesTest" rev="latest.integration" conf="test->test"/>
	</dependencies>
</ivy-module>
