<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<ivy-module version="2.0"> 
    <info organisation="org.apache.easyant.plugins"
           module="package-test-jar"
           status="milestone"
           revision="0.1">
           <description>
                <p>This module provides jar packaging feature for tests.</p>
                <p>
                    You can bind targets of this plugin to package phase by using bindtarget element in your module.ivy file.
                    Example : 
                    <code type="xml">
                        <plugin name="package-test-jar" rev="0.1" as="test-jar"/>
                        <bindtarget target="test-jar:jar" tophase="package"/>
                    </code>
                    Or as a nested element of the plugin
                    <code type="xml">
                        <plugin name="package-test-jar" rev="0.1" as="test-jar">
                            <!-- here, the target prefix is not mandatory as easyant can determine it from plugin element -->
                            <bindtarget target=":jar" tophase="package"/>
                        </plugin>
                    </code>
                    
                </p>
                 
           </description>
    </info>
    <publications>
        <artifact type="ant" />
    </publications>
</ivy-module>
