<!--
	Copyright 2009 the EasyAnt project
	
	See the NOTICE file distributed with this work for additional information 
	regarding copyright ownership.
	
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.  
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org"> 
	<info organisation="org.apache.easyant" module="meta-build-2-test" status="integration" revision="0.2">
		<description>Tests the features of a meta-build v2 type project.</description>
		<ea:build mrid="org.apache.easyant.buildtypes#meta-build;0.2">
			<ea:property name="project.ivy.settings.file" value="${basedir}/ivysettings.xml"/>
		</ea:build>
	</info>
	<configurations>
		<conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf"/>
		<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
	</configurations>
	<dependencies>
		<dependency org="junit" name="junit" rev="4.4" conf="test->default" />
	</dependencies>

</ivy-module>
